version: '3.8'

volumes:
  sso-postgres-data:
    driver: local
  booking-management-postgres-data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
    
services:
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    
  nginx:
    image: nginx
    
  booking-management-ui:
    image: booking-management-ui:${MY_TAG:-latest}
    build:
      context: clients
      dockerfile: Dockerfile
    expose:
      - "80"
      
  booking-management-postgres:
    image: postgres
    volumes:
      - booking-management-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: password
      
  booking-management-api:
    image: booking-management-api:${MY_TAG:-latest}
    build:
      context: services
      dockerfile: BookingManagement/BookingManagementService.API/Dockerfile
      target: "build"
    expose:
      - "80"
    working_dir: "/app"
    entrypoint:
      - "dotnet"
      - "BookingManagementService.API.dll"
    depends_on:
      - cinema-booking-cache
      - logger-seq
      - rabbitmq
  
  cinema-booking-cache:
    image: redis:latest
    restart: unless-stopped
    volumes:
          - ./path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    command: >
      - notify-keyspace-events Ex
      
  logger-seq:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: Y
  
  sso-postgres:
    image: postgres
    volumes:
      - sso-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  
  sso:
    image: quay.io/keycloak/keycloak:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .data/keycloak:/opt/keycloak/data/h2/
    command:
      - start-dev
      - --http-port=80
      - --proxy edge
    environment:
      DB: postgres
      KC_DB_URL: 'jdbc:postgresql://sso-postgres:5432/keycloak'
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB: postgres
      KEYCLOAK_STATISTICS: all
      KEYCLOAK_LOGLEVEL: DEBUG
      PROXY_ADDRESS_FORWARDING: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: change_me
    depends_on:
      - sso-postgres
        
  prometheus:
    image: prom/prometheus
    volumes:
      - ./build/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    
  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./build/grafana/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - prometheus    
        
  otel-collector:
    image: otel/opentelemetry-collector
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./build/otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # gRPC
      - "4318:4318" # HTTP
      - "8889:8889" # HTTP pprof
      - "8888:8888" # HTTP pprof
    